# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Afiq/project/EEE542/miniproject_final/miniproject_final.cache/wt [current_project]
set_property parent.project_path C:/Users/Afiq/project/EEE542/miniproject_final/miniproject_final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
read_verilog -library xil_defaultlib C:/Users/Afiq/project/EEE542/miniproject_final/miniproject_final.srcs/sources_1/new/arbiter_1p0.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top arbiter_1p0 -part xc7z010clg400-1


write_checkpoint -force -noxdef arbiter_1p0.dcp

catch { report_utilization -file arbiter_1p0_utilization_synth.rpt -pb arbiter_1p0_utilization_synth.pb }
